### ISSUE TITLE
No returning Bitmap with static images

### ISSUE THREAD

**Issue by Stealth01** [0x2E757/ScreenCapturer#1]
When a static image is on the screen, MakeScreenshot does not return any bitmap and hang the process until a change occurs (like cursor moving). StartCapturing does not hang the process but does not return any bitmap.

**Comment by 0x2E757** [comment]
This is because how SharpDX is working. There is listener for changes on screen, which is used in this library. Seems like in your case you need to use `Graphics.CopyFromScreen`, which immediately makes copy of actual screen state. ScreenCapturer is better than `Graphics.CopyFromScreen` only if you need maximize program performance and get next screen snapshot as soon as possible, meanwhile using `Graphics.CopyFromScreen` it's not possible. You can use timers, but it will make 5-20 ms delay comparing ScreenCapturer. Also ScreenCapturer will prevent making screenshot with no changes comparing to previous.

**Comment by 0x2E757** [comment]
There is dirty workaround with `MakeScreenshot` method, using small timeout value and second bitmap for `Graphics.CopyFromScreen`.
```C#
static Bitmap bmp = new Bitmap(Screen.PrimaryScreen.Bounds.Width, Screen.PrimaryScreen.Bounds.Height);
static Graphics g = Graphics.FromImage(bmp);

public Bitmap MakeScreenshotWrapper() {
    Int32 displayIndex = 0;
    Int32 adapterIndex = 0;
    Int32 timeout = 50;
    try {
        return ScreenCapturer.MakeScreenshot(displayIndex, adapterIndex, timeout);
    } catch (SharpDX.SharpDXException ex) {
        // Check for DXGI_ERROR_WAIT_TIMEOUT/WaitTimeout exception
        if (ex.HResult == -2005270489) {
            g.CopyFromScreen(Screen.PrimaryScreen.Bounds.X, Screen.PrimaryScreen.Bounds.Y, 0, 0, bmp.Size, CopyPixelOperation.SourceCopy);
            return bmp;
        } else {
            throw ex;
        }
    }
} 
```
But as seems to me it's better to use just `Graphics.CopyFromScreen`.

**Comment by Stealth01** [comment]
Thanks for the quick reply and the sample code!
CopyFromScreen is the best solution for a single screenshot, but my goal is to continuously duplicate a screen in a window.
One possible solution is to create an initial screenshot with CopyFromScreen and then use ScreenCapturer.StartCapturing.
However, there is another problem: if the screen shows a static image for a longer time than the timeout (e.g. when a video is paused), a exception occurs and the program crashes. To avoid this, I modified the ThreadMain method by adding a try-catch: 
```c#
private static void ThreadMain(Action<Bitmap> onCaptured, Int32 minimalDelay, Int32 displayIndex, Int32 adapterIndex, Int32 maxTimeout) {
    Stopwatch stopwatch = new Stopwatch(); 
    while (CaptureActive) {
        stopwatch.Restart();
        Bitmap = new Bitmap(Width, Height, PixelFormat.Format32bppRgb);
        try
        {
            InnerMakeScreenshot(displayIndex, adapterIndex, maxTimeout);
        }
        catch (SharpDXException ex) when (ex.HResult == -2005270489)
        {
            Bitmap.Dispose();
            continue;
        };
        if (CaptureActive && CallbackEnabled) onCaptured(Bitmap);
        Thread.Sleep((Int32)Math.Max(minimalDelay - stopwatch.ElapsedMilliseconds, 0));
    }
}
```
Could this change cause problems?

**Comment by 0x2E757** [comment]
Yes, that should work fine. Don't forget to dispose unused bitmap before `continue` to prevent memory leaks.

**Comment by Stealth01** [comment]
Yes, I edited the previos message adding `Bitmap.Dispose()`.
