### ISSUE TITLE
why removed "MakeScreenshot()"

### ISSUE THREAD

**Issue by a11s** [0x2E757/ScreenCapturer#4]
I upgrade v2.0. 
build and found error. MakeScreenshot disappeared.
synchronized "MakeScreenshot" is very useful for me. even it blackscreen sometimes.
hope it return back.

**Comment by 0x2E757** [comment]
Hi. `MakeScreenshot` function was removed becase it wasn't really doing a screenshot, it was awaiting and capturing upcoming screen changes. For making actual screenshot you should use native C# function `CopyFromScreen` (`Graphics` class object's method). Also it was badly compatible with display context changes (resolution change, display relative position in system and etc. changes). But you can just keep using older version of this library.

**Comment by camhart** [comment]
CopyFromSource doesn't capture certain content where this library does (DirectX games for example).  So there are use cases for using this library instead of CopyFromSource.

**Comment by 0x2E757** [comment]
> CopyFromSource doesn't capture certain content where this library does (DirectX games for example). So there are use cases for using this library instead of CopyFromSource.

Good point. Then maybe in future I'll add a function for making single screen snapshot.
