### ISSUE TITLE
Bug windows 10 

### ISSUE THREAD

**Issue by logwlogw** [0x2E757/ScreenCapturer#7]
Hi,
---------------
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            ScreenCapturer.StartCapture((Bitmap bitmap) => {
                // Process image (bitmap) here
            });
        }
    }
---------------
If you press ctrl+alt+del the program will crash
SharpDX.SharpDXException: "HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall], 

Net framework, 4.7.8, and Net core also

**Comment by 0x2E757** [comment]
It's [SharpDX](http://sharpdx.org/) exception, not the library. The best thing I could suggest is to wrap your program with try catch.
